### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by nojaf** [TheSpyder/rescript-webapi#135]
Hello,

How would one combine these bindings with the React event handlers?

```res
@react.component
let make = () => {
  let (firstName, setFirstName) = React.useState(_ => "")
  let onChange = ev => {
    let target = ev->ReactEvent.Form.target // target is  {..}, how to make it something from rescript-webapi
    setFirstName(_ => target->value) // to do something like this...
  }

  <input type_="text" value={firstName} onChange placeholder="first name" />
}
```

this is a big missing link in my ReScript learnings so far.

**Comment by TheSpyder** [comment]
The React bindings explicitly do not support target types so the best you can do `target["value"]`.

If you're _really_ keen on it, you can define a generic external:
```
external unsafeAsHtmlElement: 'a => Dom.htmlElement = "%identity"

let target = let target = ev->ReactEvent.Form.target->unsafeAsHtmlElement
setFirstName(_ => target->Webapi.Dom.HtmlElement.value)
```

**Comment by nojaf** [comment]
> The React bindings explicitly do not support target types so the best you can do target["value"].

It still don't quite grasp the rational there. I guess a generic type would have also been useful instead.

Anyway, thanks for the example, much appreciated!

**Comment by TheSpyder** [comment]
> It still don't quite grasp the rational there

The thinking of the ReScript compiler team has evolved over time. `webapi` started as an internal project but was spun out when they decided it was not possible to make fully correct web api bindings.

That's around the time those APIs were written; the thinking was that every project is so different developers should write their own custom bindings or use the DOM like pure JavaScript.

I disagree, clearly, which is why I took on responsibility for this project 😉 

Things might be evolving back in the other direction, but if that doesn't happen I'll still be here.
